# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eae21d8e0a6635f526b8270477353856f7071af51299a2d3fcb59a6e0947215a50083155aa3e4b3b4a93c4fc38d3229024db4d27153d5744972cb3eb25a625d

test:
  secret_key_base: b5062d48359dd56e3f905110075404e63912e92fa85e5e49370d42f42c4e9dab2a4ffea415131f478f0fa248661b92b7c14e05f16b1de306d50ab4f50125b384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
